area:
  x_max: 100
  x_min: 0
  y_max: 50
  y_min: 0
goal:
  x_loc: 80
  y_loc: 30
obstacles:
- acc_x: 0
  acc_y: 0
  centroid_x: 0
  centroid_y: 25
  dx: 0
  dy: 50
  orientation: 0
  velocity_x: 0
  velocity_y: 0
- acc_x: 0
  acc_y: 0
  centroid_x: 100
  centroid_y: 25
  dx: 0
  dy: 50
  orientation: 0
  velocity_x: 0
  velocity_y: 0
- acc_x: 0
  acc_y: 0
  centroid_x: 50
  centroid_y: 0
  dx: 100
  dy: 0
  orientation: 0
  velocity_x: 0
  velocity_y: 0
- acc_x: 0
  acc_y: 0
  centroid_x: 50
  centroid_y: 50
  dx: 100
  dy: 0
  orientation: 0
  velocity_x: 0
  velocity_y: 0
- acc_x: 0
  acc_y: 0
  centroid_x: 50
  centroid_y: 25
  dx: 5
  dy: 10
  orientation: 0
  velocity_x: 0
  velocity_y: 5
robot:
  centroid_x: 10
  centroid_y: 10
  orientation: 45
  velocity: 5
